### PR TITLE
Added link to ML SIG

### PR DESCRIPTION
**Pull request by dmueller2001**
Added link to ML SIG

### CODE REVIEW

**Comment by vishh** [comment]
We haven't decided to run this project as part of openshift ML sig yet. We are planning on starting with SIG apps in k8s to find a home for it. 
Can we hold off this PR until the community decides on that?

**Comment by ddysher** [comment]
@vishh  SIG apps is pretty big; it is hard to both coordinating and to find related information there.  Are you planning to actually merge this to SIG apps, or just to talk with them?

**Comment by foxish** [comment]
I think the idea for now was to figure out interest in different related
sigs. A new ML SIG in k8s was also discussed as a potential avenue to
collaborate on this effort.

On Dec 9, 2017 3:13 PM, "Deyuan Deng" <notifications@github.com> wrote:

@vishh <https://github.com/vishh> SIG apps is pretty big; it is hard to
both coordinating and to find related information there. Are you planning
to actually merge this to SIG apps, or just to talk with them?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/kubeflow/pull/24#issuecomment-350505934>, or mute
the thread

**Comment by dmueller2001** [comment]
I've been added to the Red Hat signed Google CLA

**Comment by jlewi** [comment]
@dmueller2001 Thanks for the PR. Per the discussion above. I'm going to close this for now. I believe the plan is to have a community meeting this month and decide how we want to coordinate this project. Based on that meeting will update the docs accordingly.

**Pull request closed without merging**
