### PR TITLE
fix prow_artifacts.py

### PR DESCRIPTION
**Pull request by lluunn**
There is a missing argument, bucket, what will lead to KeyError.

### CODE REVIEW

**Comment by jlewi** [comment]
Please rebase and make the PR description a bit more descriptive (i.e. what was the bug).
LGTM

**Comment by lluunn** [comment]
Done.

**Comment by jlewi** [comment]
Looks like you need to resync again; probably because of your other PR which I just merged.

**Comment by lluunn** [comment]
Should be fixed now.

**Pull request merged**
