### PR TITLE
Adding Helm chart for deployment

### PR DESCRIPTION
**Pull request by sozercan**
* Provides toggles for model server, Jupyterhub, TfJob crd, and RBAC
* Configurable image options and model server settings (model base path, port, etc)
* Configurable cloud provider settings

### CODE REVIEW

**Comment by sozercan** [comment]
I signed it!

**Comment by jlewi** [comment]
Thanks for this.

Have you seen the latest work using ksonnet to deploy and manage Kubeflow? The update to the instructions is still pending in #45.

What are your thoughts on using helm vs. ksonnet?

**Comment by sozercan** [comment]
@jlewi sorry about the delay, was off for holidays. I haven't looked at the kubeflow ksonnet deployment flow before the merge, just looking at it now. 

should we still add helm chart and instructions?

**Comment by jlewi** [comment]
What would be the benefit of supporting helm and ksonnet? How would we keep them in sync?

**Comment by nkashy1** [comment]
@jlewi : The [blog post](http://blog.kubernetes.io/2017/12/introducing-kubeflow-composable.html) announcing kubeflow states that helm is integrating ksonnet. Two questions:

1. Will that moot the question of syncing?

2. Will that make this work redundant?

**Comment by jlewi** [comment]
@sozercan Any chance to look into ksonnet?

@nkashy1 Not sure. I haven't looked in detail to see what the plans are for ksonnet, helm, and app management.

**Comment by bhack** [comment]
Take a look at https://github.com/kubernetes/helm/issues/2577.
And for the development phase https://github.com/Azure/draft/issues/482

**Comment by jlewi** [comment]
Going to close this issue for now. Feel free to reopen it if you want to continue .

**Comment by sylus** [comment]
@sozercan have you considered pushing the helm chart over to https://github.com/kubernetes/charts and we can then have it there?

Would be great once ksonnet is added to helm but at least in my opinion I think helm should be the defacto standard way to do this at least for newcomers given its community size and number of applications that can be easily deployed. Though anything heptio touches is frankly amazing so gather this was a hard choice. :)

**Pull request closed without merging**
