### PR TITLE
update tf-cnn example use terminationPolicy to address not using master replica

### PR DESCRIPTION
**Pull request by yupbank**
* Related to #192 
* Now that terminationPolicy can be used to specify a non-master chief, we no longer need to add a master to run the tf-cnn we can just use worker 0 as the chief which allows the example to run out of the box.

### CODE REVIEW

**Comment by jlewi** [comment]
This is great; thank you so much for contributing?

/ok-to-test

Can you update our ksonnet prototype?
https://github.com/google/kubeflow/blob/master/kubeflow/tf-job/prototypes/tf-cnn-benchmarks.jsonnet

**Comment by yupbank** [comment]
> Can you update our ksonnet prototype?

a second PR or just one PR for doing both?

**Comment by jlewi** [comment]
@yupbank Whatever works for you. If you want to submit this first that works for me. Lets just leave the issue open until the ksonnet files are updated.

**Comment by jlewi** [comment]
@yupbank If you want to submit this first please merge in latest changes and update the PR and let me know and I'll merge it.

**Comment by yupbank** [comment]
let's merge this one first :)

thanks !

**Comment by jlewi** [comment]
* Related to #192

* Now that terminationPolicy can be used to specify a non-master chief, we no longer need to add a master to run the tf-cnn we can just use worker 0 as the chief which allows the example to run out of the box.

**Comment by jlewi** [comment]
I did not intend to make that last comment; that was supposed to be the commit message.

**Pull request merged**
